name: Criar release do Online

on:
  push:
    paths:
      - "VERSION"
    branches:
      - main
  workflow_dispatch:

jobs:
  release-online:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Ler versÃ£o do online
        id: version
        run: |
          CODENAME=$(awk '{print $1}' VERSION)
          VERSION=$(awk '{print $2}' VERSION)
          echo "codename=$CODENAME" >> $GITHUB_OUTPUT
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Ler CHANGELOG do online
        id: changelog_online
        run: |
          if [ -f CHANGELOG.md ]; then
            cat CHANGELOG.md > online_changelog.txt
          else
            echo "Sem changelog do online." > online_changelog.txt
          fi
          echo "online_body<<EOF" >> $GITHUB_OUTPUT
          cat online_changelog.txt >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Ler CHANGELOG do core
        id: changelog_core
        run: |
          if [ -f core/CHANGELOG.md ]; then
            cat core/CHANGELOG.md > core_changelog.txt
          else
            echo "Sem changelog do core." > core_changelog.txt
          fi
          echo "core_body<<EOF" >> $GITHUB_OUTPUT
          cat core_changelog.txt >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Criar Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ steps.version.outputs.version }}
          release_name: "${{ steps.version.outputs.codename }} ${{ steps.version.outputs.version }}"
          body: |
            Changelog do online:
            ${{ steps.changelog_online.outputs.online_body }}

            Changelog do core:
            ${{ steps.changelog_core.outputs.core_body }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_GITHUB_TOKEN }}
